version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- pwsh: >-
    dotnet restore Identity.MongoDb.sln

build:
  project: Identity.MongoDb.sln
  verbosity: minimal
  
after_build:
- pwsh: >-
    .paket/paket.exe pack . --template ./IdentityMongoDb/paket.template

    nuget push *.nupkg -ApiKey o3yk865auhn9olmkxtmn2v49 -Source https://ci.appveyor.com/nuget/salda8-0h4n5nbbutro/api/v2/package

    nuget push *.nupkg 91b4b205-d68e-4a90-98db-6ce420617a14 -Source https://www.myget.org/F/salda/api/v2/package

on_success:
- ps: >-
    $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
        Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
        bash codecov.sh -f "coverage.xml"