version: 1.0.{build}
image: Visual Studio 2017
build_script:
- ps: ./buildWithCi.ps1
  
after_build:
- pwsh: >-
    .paket/paket.exe pack . --template ./IdentityMongoDb/paket.template

    nuget push *.nupkg -ApiKey o3yk865auhn9olmkxtmn2v49 -Source https://ci.appveyor.com/nuget/salda8-0h4n5nbbutro/api/v2/package

    nuget push *.nupkg 91b4b205-d68e-4a90-98db-6ce420617a14 -Source https://www.myget.org/F/salda/api/v2/package
    
    Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
    
    .\codecov.sh -f "coverage.xml"
